[package]
name = "day05"
version = "0.1.0"
authors = ["Andrés Sánchez <andres.sanchez@epfl.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "*"